---
apiVersion: v1
kind: Service
metadata:
  name: flask-todoapp
  namespace: default
spec:
  selector:
    app: flask-todoapp
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 5000
    port: 80
